using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MEnglish
{
    public class GlobalDic
    {
        public static string[] EnWordsArray =
        {
            "hello",
            "apple",
            "bye",
            "bridge",
            "jungle",
            "forest",
            "animal",
            "area",
            "book",
            "camera",
            "coffee",
            "end",
            "eye",
            "farm",
            "feet",
            "fire",
            "food",
            "grow",
            "half",
            "hand",
            "help",
            "horse",
            "idea",
            "land",
            "letter",
            "mint",
            "near",
            "need",
            "order",
            "part",
            "plant",
            "round",
            "sea",
            "small",
            "star",
            "strawberry",
            "study",
            "surface",
            "table",
            "tea",
            "time",
            "walk",
            "watch",
            "way",
            "wind",
            "write",
            "ask for",
            "be out",
            "break down",
            "break into",
            "burst out",
            "clean up",
            "check in",
            "check out",
            "call back",
            "keep away",
            "wake up",
            "watch out",
            "work off",
            "work out",
            "write down",
            "write up",
            "tends",
            "often",
            "entirely",
            "miscellaneous",
            "split",
            "proper",
            "amount",
            "contributor",
            "issue",
            "beware",
            "milk",
            "sound"
        };
        public static string[] RuWordsArray =
        {
            "привет",
            "яблоко",
            "пока",
            "мост",
            "джунгли",
            "лес",
            "животное",
            "зона",
            "книга",
            "камера",
            "кофе",
            "конец",
            "глаз",
            "ферма",
            "ноги",
            "огонь",
            "еда",
            "расти",
            "половина",
            "рука",
            "помощь",
            "лошадь",
            "идея",
            "земля",
            "письмо",
            "мята",
            "близко",
            "необходимость",
            "порядок",
            "часть",
            "растение",
            "круглый",
            "море",
            "маленький",
            "звезда",
            "клубника",
            "изучать",
            "поверхность",
            "стол",
            "чай",
            "время",
            "прогулка",
            "часы",
            "путь",
            "ветер",
            "писать",
            "просить, спрашивать, требовать",
            "отсутствовать",
            "сломать, сломаться, перестать работать",
            "врываться, вломиться",
            "окликнуть, разразиться смехом, внезапно начинаться",
            "чистить, убирать, приводить в порядок",
            "зарегистрироваться",
            "проверить, выписаться",
            "перезвонить",
            "не подходите",
            "будить, просыпаться, бодрствовать",
            "осторожно, быть начеку, настороже",
            "отработать, отделаться, освободиться",
            "определить, вычислить, добиться, получаться, тренироваться",
            "записать на бумаге",
            "дописать, придать законченный вид",
            "как правило",
            "довольно часто",
            "полностью",
            "разное",
            "разделенный",
            "правильный",
            "количество",
            "участник",
            "проблема",
            "остерегаться",
            "молоко",
            "звук"
        };
        public static string[] GreatArray =
        {
            "отлично 🙌",
            "превосходно 😍",
            "молодец 👏",
            "так держать 👌",
            "правильно 👍",
            "успешно 😎",
            "да 🎉",
            "точно 💪"
        };
        public static string[] BadArray =
        {
            "попробуй еще раз 🤨",
            "ошибка 🙄",
            "нет 😶",
            "все получится ✌",
            "еще попытка ✍",
            "не подходит 🙅‍♀️",
            "воспользуйся подсказкой 💡"
        };
    }
}
